### ISSUE TITLE
repo with same name

### ISSUE THREAD

**Issue by Nikoloutsos** [jimfilippou/jimfilippou#1]
Πρωτη φορα βλεπω να φτιαχουν ριπο με το ονομα τους :P

**Comment by jimfilippou** [comment]
It's an easter egg bro, check this out https://github.com/jimfilippou
<img width="1048" alt="Screenshot 2020-07-10 at 3 08 34 PM" src="https://user-images.githubusercontent.com/6877046/87152937-488d8e00-c2bf-11ea-8230-4d6a92430a40.png">

**Comment by Nikoloutsos** [comment]
Damn I did not know that, good to know!
